src/Entity/Logboek.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LogboekRepository")
 */
class Logboek
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $userId;

    /**
     * @ORM\Column(type="integer")
     */
    private $brief_nr;

    /**
     * @ORM\Column(type="date")
     */
    private $datum;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $chauffeurId;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Truck")
     * @ORM\JoinColumn(nullable=false)
     */
    private $truckId;

    /**
     * @ORM\Column(type="integer")
     */
    private $kubs;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $laadplaats;

    /**
     * @ORM\Column(type="time")
     */
    private $vertrektijd;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $bestemming;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $evenement;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?int
    {
        return $this->userId;
    }

    public function setUserId(int $userId): self
    {
        $this->userId = $userId;

        return $this;
    }

    public function getBriefNr(): ?int
    {
        return $this->brief_nr;
    }

    public function setBriefNr(int $brief_nr): self
    {
        $this->brief_nr = $brief_nr;

        return $this;
    }

    public function getDatum(): ?\DateTimeInterface
    {
        return $this->datum;
    }

    public function setDatum(\DateTimeInterface $datum): self
    {
        $this->datum = $datum;

        return $this;
    }

    public function getChauffeurId(): ?int
    {
        return $this->chauffeurId;
    }

    public function setChauffeurId(?int $chauffeurId): self
    {
        $this->chauffeurId = $chauffeurId;

        return $this;
    }

    public function getTruckId(): ?Truck
    {
        return $this->truckId;
    }

    public function setTruckId(?Truck $truckId): self
    {
        $this->truckId = $truckId;

        return $this;
    }

    public function getKubs(): ?int
    {
        return $this->kubs;
    }

    public function setKubs(int $kubs): self
    {
        $this->kubs = $kubs;

        return $this;
    }

    public function getLaadplaats(): ?string
    {
        return $this->laadplaats;
    }

    public function setLaadplaats(string $laadplaats): self
    {
        $this->laadplaats = $laadplaats;

        return $this;
    }

    public function getVertrektijd(): ?\DateTimeInterface
    {
        return $this->vertrektijd;
    }

    public function setVertrektijd(\DateTimeInterface $vertrektijd): self
    {
        $this->vertrektijd = $vertrektijd;

        return $this;
    }

    public function getBestemming(): ?string
    {
        return $this->bestemming;
    }

    public function setBestemming(string $bestemming): self
    {
        $this->bestemming = $bestemming;

        return $this;
    }

    public function getEvenement(): ?string
    {
        return $this->evenement;
    }

    public function setEvenement(string $evenement): self
    {
        $this->evenement = $evenement;

        return $this;
    }
}

src/Form/LogboekType.php
<?php

namespace App\Form;

use App\Entity\Logboek;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LogboekType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('userId')
            ->add('brief_nr')
            ->add('datum')
            ->add('chauffeurId')
            ->add('kubs')
            ->add('laadplaats')
            ->add('vertrektijd')
            ->add('bestemming')
            ->add('evenement')
            ->add('truckId')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Logboek::class,
        ]);
    }
}

src/Controller/LogboekController.php
<?php

namespace App\Controller;

use App\Entity\Logboek;
use App\Form\LogboekType;
use App\Repository\LogboekRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/logboek")
 */
class LogboekController extends AbstractController
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;

    }
    /**
     * @Route("/", name="logboek_index", methods={"GET"})
     */
    public function index(LogboekRepository $logboekRepository): Response
    {
        if (!$this->security->isGranted('ROLE_ADMIN')) {
            $user=$this->security->getUser();
            if (!$user){
                return $this->redirectToRoute('default');
            }
            return $this->render('logboek/index.html.twig', [
                'logboeks' => $logboekRepository->findBy(['userId'=>$this->security->getUser()->getId()]),
            ]);
        }
        return $this->render('logboek/index.html.twig', [
            'logboeks' => $logboekRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="logboek_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $logboek = new Logboek();
        $logboek->setUserId($this->security->getUser()->getId());
        $form = $this->createForm(LogboekType::class, $logboek);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($logboek);
            $entityManager->flush();

            return $this->redirectToRoute('logboek_index');
        }

        return $this->render('logboek/new.html.twig', [
            'logboek' => $logboek,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="logboek_show", methods={"GET"})
     */
    public function show(Logboek $logboek): Response
    {
        return $this->render('logboek/show.html.twig', [
            'logboek' => $logboek,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="logboek_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Logboek $logboek): Response
    {
        $form = $this->createForm(LogboekType::class, $logboek);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('logboek_index', [
                'id' => $logboek->getId(),
            ]);
        }

        return $this->render('logboek/edit.html.twig', [
            'logboek' => $logboek,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="logboek_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Logboek $logboek): Response
    {
        if ($this->isCsrfTokenValid('delete'.$logboek->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($logboek);
            $entityManager->flush();
        }

        return $this->redirectToRoute('logboek_index');
    }
}

templates/logboek/_delete_form.html.twig
<form method="post" action="{{ path('logboek_delete', {'id': logboek.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ logboek.id) }}">
    <button class="btn">Delete</button>
</form>

templates/logboek/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/logboek/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Logboek{% endblock %}

{% block body %}
    <h1>Edit Logboek</h1>

    {{ include('logboek/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('logboek_index') }}">back to list</a>

    {{ include('logboek/_delete_form.html.twig') }}
{% endblock %}

templates/logboek/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Logboek index{% endblock %}

{% block body %}
    <h1>Logboek index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>UserId</th>
                <th>Brief_nr</th>
                <th>Datum</th>
                <th>ChauffeurId</th>
                <th>Kubs</th>
                <th>Laadplaats</th>
                <th>Vertrektijd</th>
                <th>Bestemming</th>
                <th>Evenement</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for logboek in logboeks %}
            <tr>
                <td>{{ logboek.id }}</td>
                <td>{{ logboek.userId }}</td>
                <td>{{ logboek.briefNr }}</td>
                <td>{{ logboek.datum ? logboek.datum|date('Y-m-d') : '' }}</td>
                <td>{{ logboek.chauffeurId }}</td>
                <td>{{ logboek.kubs }}</td>
                <td>{{ logboek.laadplaats }}</td>
                <td>{{ logboek.vertrektijd ? logboek.vertrektijd|date('H:i:s') : '' }}</td>
                <td>{{ logboek.bestemming }}</td>
                <td>{{ logboek.evenement }}</td>
                <td>
                    <a href="{{ path('logboek_show', {'id': logboek.id}) }}">show</a>
                    <a href="{{ path('logboek_edit', {'id': logboek.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('logboek_new') }}">Create new</a>
{% endblock %}

templates/logboek/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Logboek{% endblock %}

{% block body %}
    <h1>Create new Logboek</h1>

    {{ include('logboek/_form.html.twig') }}

    <a href="{{ path('logboek_index') }}">back to list</a>
{% endblock %}

templates/logboek/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Logboek{% endblock %}

{% block body %}
    <h1>Logboek</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ logboek.id }}</td>
            </tr>
            <tr>
                <th>UserId</th>
                <td>{{ logboek.userId }}</td>
            </tr>
            <tr>
                <th>Brief_nr</th>
                <td>{{ logboek.briefNr }}</td>
            </tr>
            <tr>
                <th>Datum</th>
                <td>{{ logboek.datum ? logboek.datum|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>ChauffeurId</th>
                <td>{{ logboek.chauffeurId }}</td>
            </tr>
            <tr>
                <th>Kubs</th>
                <td>{{ logboek.kubs }}</td>
            </tr>
            <tr>
                <th>Laadplaats</th>
                <td>{{ logboek.laadplaats }}</td>
            </tr>
            <tr>
                <th>Vertrektijd</th>
                <td>{{ logboek.vertrektijd ? logboek.vertrektijd|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Bestemming</th>
                <td>{{ logboek.bestemming }}</td>
            </tr>
            <tr>
                <th>Evenement</th>
                <td>{{ logboek.evenement }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('logboek_index') }}">back to list</a>

    <a href="{{ path('logboek_edit', {'id': logboek.id}) }}">edit</a>

    {{ include('logboek/_delete_form.html.twig') }}
{% endblock %}